# Generated by Django 3.0 on 2020-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200127_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='posted_under',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='page',
            name='publish',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
