# Generated by Django 3.0 on 2020-01-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200127_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='publish',
            field=models.IntegerField(default=0),
        ),
    ]
