# Generated by Django 3.0 on 2020-01-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200127_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu_title',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
