# Generated by Django 3.0 on 2020-01-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20200128_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='website',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
