# Generated by Django 3.0 on 2020-01-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_setting_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page_url',
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
