# Generated by Django 3.0 on 2020-02-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
