# Generated by Django 3.0 on 2020-02-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20200201_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='link',
            new_name='video_link',
        ),
    ]
