# Generated by Django 3.0 on 2020-02-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20200201_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
