# Generated by Django 3.0 on 2020-02-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20200201_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
