# Generated by Django 3.0 on 2020-02-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='post.jpg', null=True, upload_to='images/'),
        ),
    ]
