# Generated by Django 3.0 on 2020-02-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20200218_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page'),
        ),
    ]
