# Generated by Django 3.0 on 2020-02-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20200224_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='Stories',
        ),
    ]
