# Generated by Django 3.0 on 2020-02-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_auto_20200225_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='video_link',
            field=models.URLField(default=None, null=True),
        ),
    ]
