# Generated by Django 3.0 on 2020-02-28 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_auto_20200225_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page'),
        ),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='menu',
    #         name='page',
    #         field=models.ForeignKey(default='Null', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page'),
    #     ),
    # ]
