# Generated by Django 3.0 on 2020-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_auto_20200228_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(default='wavy.mp4', null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default=None)),
                ('link', models.URLField(default=None)),
                ('section1', models.TextField(default=None)),
                ('section2', models.TextField(default=None)),
                ('footer', models.TextField(default=None)),
                ('copyright_text', models.TextField(default=None)),
            ],
        ),
    ]
