# Generated by Django 3.0 on 2020-03-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_auto_20200303_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesettings',
            name='active',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
