# Generated by Django 3.0 on 2020-03-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20200303_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homesettings',
            old_name='mini_header',
            new_name='mini_header_right',
        ),
        migrations.AddField(
            model_name='homesettings',
            name='email',
            field=models.EmailField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homesettings',
            name='phone',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
