# Generated by Django 3.0 on 2020-03-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_auto_20200303_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesettings',
            name='video',
            field=models.FileField(default='wavy.mp4', null=True, upload_to='media/'),
        ),
    ]
