# Generated by Django 3.0 on 2020-01-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
